# Generated by Django 4.0.5 on 2022-06-11 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('uri', models.URLField(max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='filesystem.directory')),
            ],
            options={
                'ordering': ('name', 'updated_at'),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=50)),
                ('uri', models.URLField(max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesystem.directory', verbose_name='directory')),
            ],
            options={
                'ordering': ('name', 'updated_at'),
            },
        ),
    ]
